# mvn clean install
# docker-compose up
# curl --insecure https://localhost:8081/actuator/health

version: '3'

services:
  springboot-service:
    image: 'springboot-image-demo:latest'
    build:
      context: .
    container_name: springboot-service
    ports:
     - '8000:8000'
     - '8080:8080'
     - '8081:8081'
     - '8443:8443'
    env_file:
      - docker-compose-env.txt
    volumes:
       - service-config:/opt/service/config
       - service-logs:/opt/service/logs
       - service-ssl:/opt/service/ssl

volumes:
  service-config:
  service-logs:
  service-ssl: